data = [
  {
    rank: 1,
    title: "",
    thumbnail: "",
    rating: "",
    id: "",
    year: 1972,
    image: "",
    description: "",
    trailer: "",
    genre: [""],
    director: [""],
    writers: ["", ")"],
    imdbid: "",
    type: "movie",
  },
  {
    rank: 2,
    title: "",
    thumbnail: "",
    rating: "",
    id: "",
    year: 1972,
    image: "",
    description: "",
    trailer: "",
    genre: [""],
    director: [""],
    writers: ["", ")"],
    imdbid: "",
    type: "show",
  },
  {
    rank: 3,
    title: "",
    thumbnail: "",
    rating: "",
    id: "",
    year: 1972,
    image: "",
    description: "",
    trailer: "",
    genre: [""],
    director: [""],
    writers: ["", ")"],
    imdbid: "",
    type: "cartoon",
  },
  {
    rank: 4,
    title: "",
    thumbnail: "",
    rating: "",
    id: "",
    year: 1972,
    image: "",
    description: "",
    trailer: "",
    genre: [""],
    director: [""],
    writers: ["", ")"],
    imdbid: "",
    type: "movie",
  },
  {
    rank: 5,
    title: "",
    thumbnail: "",
    rating: "",
    id: "",
    year: 1972,
    image: "",
    description: "",
    trailer: "",
    genre: [""],
    director: [""],
    writers: ["", ")"],
    imdbid: "",
    type: "show",
  },
];
